### ISSUE TITLE
WordPress Update - 6.1.1

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#490]
- [x] Developer: [Generate update script](https://github.com/MESH-Research/hc-admin-docs-support/blob/main/documentation/developer/how-tos/updating-wordpress.md#updating-wordpress-1)
- [x] Developer: Update development server for testing
- [x] Developer: Ensure WordPress loads, has basic functionality
- [x] Testing: Run full test protocol
    - Any potential problems should be checked against production and then be registered as separate issues within the update epic.
- [x] Developer: All update issues have been addressed
- [x] Developer: Update script has been revised based on testing
- [x] Developer: Run updates on production
- [x] Testing: Run abbreviated test protocol to ensure core functionality
