### ISSUE TITLE
[Project] Decouple HC from BuddyBoss

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#564]
## Description ##

The aim of this project is to move the Humanities Commons base sites off of BuddyBoss and our boss-child child theme in favor of a modern theme (tentatively 2023). Upon successful completion, the boss-child theme will be retired while retaining all of the current functionality.

## Background ##

Humanities Commons is a "multi-network" WordPress / BuddyPress site, meaning that there are not just multiple individual WordPress sites run from the same instance, but multiple "networks" of sites. Each network is composed of a base site and user sites. The networks are:

- Humanities Commons (base site: [hcommons.org](https://hcommons.org), user sites *.hcommons.org)
- MLA Commons (base site: [mla.hcommons.org](https://mla.hcommons.org), user sites *.mla.hcommons.org)
- ARLIS/NA Commons (base site: [arlisna.hcommons.org](https://arlisna.hcommons.org), user sites *.arlisna.hcommons.org)
- HASTAC Commons (base site: [hastac.hcommons.org](https://hastac.hcommons.org), user *.hastac.hcommons.org)
- AUPresses Commons (base site: [up.hcommons.org](https://up.hcommons.org), user *.up.hcommons.org)
- SAH Commons (base site: [sah.hcommons.org](https://sah.hcommons.org), user *.sah.hcommons.org)
- MSU Commons (base site: [commons.msu.edu](https://commons.msu.edu), user *.commons.msu.edu)

Each of the base sites uses the [boss-child](https://github.com/MESH-Research/boss-child) theme, which is a child theme of BuddyBoss (v. 2.2.2).

The core Humanities Commons functionality is spread across three plugins in addition to the boss-child theme:
- [humanities-commons](https://github.com/MESH-Research/humanities-commons) --- activated network-wide, on all base and user sites. Core functionality required for all sites goes here.
- [hc-custom](https://github.com/MESH-Research/hc-custom) --- activated on base sites. Functionality specific to base sites goes here.
- [humcore](https://github.com/MESH-Research/humcore) --- activated on base sites. Implements functionality for [Fedora](https://fedora.lyrasis.org/)-based CORE repository.

(Additionally, the [commons](https://github.com/MESH-Research/commons) repository contains the base file structure of the site and must-use plugins that facilitate, for example, user authentication and domain mapping.)

The hc-custom plugin will be the plugin where most functionalities in boss-child are re-implemented. For functionality specific to the repository, changes should be made to the humcore repository.

## Required Functionalities ##

The base sites have four central components:
1. Profiles (/members)
2. Groups (/groups)
3. Sites (/sites)
4. CORE Repository (/core)

A catalog of functionalities for the sites can be found [here](https://docs.google.com/document/d/1iMEoLQywfbok94fLHKwYFbuhkpUoYFbKivsjga-imkU/edit?usp=sharing) (Google Docs). To the extent possible, all current functionalities should be preserved.

## To Do ##

Main Epic: MESH-Research/commons#534

Sub-epics & issues:

- [x] MESH-Research/hc-custom#177
    - [x] MESH-Research/hc-custom#171
    - [x] MESH-Research/hc-custom#175
    - [x] MESH-Research/hc-custom#172
    - [x] MESH-Research/hc-custom#173
    - [x] MESH-Research/hc-custom#174
    - [x] MESH-Research/hc-custom#176
- [x] MESH-Research/hc-custom#178
    - [x] MESH-Research/hc-custom#180
    - [x] MESH-Research/hc-custom#181
    - [x] MESH-Research/hc-custom#182
- [x] MESH-Research/hc-custom#184
    - [x] MESH-Research/hc-styles#8
- [x] MESH-Research/humcore#207
    - [x] MESH-Research/humcore#203
    - [x] MESH-Research/humcore#204
    - [x] MESH-Research/humcore#205
    - [x] MESH-Research/humcore#206
- Other
    - [x] MESH-Research/hc-custom#183

These should all function on all base sites.

## Target Timeline ##

- [ ] Production release: 08-01
- [ ] Production-ready: 06-30
- [ ] Testing complete: 06-15
- [ ] Ready for testing: 06-01

## Responsibilities ##

**Development Lead**: Mike
**Main Developer**: Dave
**Community Lead**: Bonnie
