### ISSUE TITLE
[Project] WordPress Overhaul

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#639]
## Description ##

The aim of this project is to improve the performance and maintainability of the current Commons WordPress site. Specifically:

### WordPress Plugin Dependency Reduction ###

[Production Plugin Inventory](https://github.com/MESH-Research/commons-docs/blob/main/documentation/developer/documentation/prod-plugin-inventory.md)

[Production Plugin Inventory - 2002 with notes](https://github.com/MESH-Research/commons-docs/blob/main/documentation/developer/documentation/prod-plugin-inventory-2022.md)

Reduce the number of plugins used by WordPress, especially those that might be causing performance issues and those that are severely out-of-date.

### WordPress theme dependency reduction ###

Reduce the number of themes used by WordPress, especially those that are out-of-date and those that do not work well with the Site Editor. This should reduce our support and testing burden as well as reducing user confusion.

### PHP 8.2 compatibility ###

Ensure that our site is compatible with PHP 8.2. PHP 7.x is no longer supported and PHP 8.x brings significant performance improvements.

### Diagnose and address performance bottlenecks ###

Once we have reduced our dependencies to a manageable level, address any remaining performance bottlenecks to the extent possible.

## To Do ##

- [ ] MESH-Research/commons#600
- [ ] MESH-Research/commons#601
- [x] MESH-Research/commons#599
- [x] MESH-Research/commons#602

## Target Timeline ##

- [ ] Plugin reduction - July 15
- [ ] Theme reduction - July 28
- [x] PHP 8.2 compatibility - July 15
- [x] Performance bottlenecks - August 31

## Responsibilities ##

**Development Lead**: Mike
**External Developer**: Dave
**Testing Lead**: Bonnie
